import streamlit as st
from datetime import date

def page_ehr_encounter():
    st.title("Encounter Notes")
    st.header("1. Patient Information")
    col1,col2,col3=st.columns(3)
    with col1: st.text_input("Patient Name")
    with col2: st.date_input("Date of Birth", value=date(1990,1,1))
    with col3: st.selectbox("Sex",["Male","Female","Other"])
    st.header("2. Encounter Details")
    st.selectbox("Visit Type",["Office Visit","Telehealth","Urgent Care","ER","Inpatient"])
    st.date_input("Encounter Date", value=date.today())
    st.header("3. Chief Complaint"); st.text_input("Chief Complaint")
    st.header("4. HPI"); st.text_area("HPI")
    st.header("5. ROS"); st.text_area("ROS")
    st.header("6. Vitals")
    colv1,colv2,colv3=st.columns(3)
    with colv1: st.text_input("Blood Pressure")
    with colv2: st.text_input("Heart Rate")
    with colv3: st.text_input("Temperature")
    st.header("7. Exam"); st.text_area("Exam Findings")
    st.header("8. Assessment & Plan"); st.text_area("Assessment"); st.text_area("Plan")
    st.header("9. ICD-10"); st.text_input("Primary ICD-10 Code")
    st.header("10. CPT"); st.text_input("CPT Code")
    if st.button("Save Encounter"): st.success("Saved (demo)")
